---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/deployment: glob:dev-*
    
spec:
  releaseName: echo-dev
  chart:
    git: git@github.com:ToviKolitz/helm-operator-update-image
    path: charts/myechochart
    ref: master
  values:
    deployment:
      image:
        repository: tovaklein/echo
        tag: dev-1.10.2
      replicaCount: 1
    ingress:
      path: "/dev"