apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
type: Opaque
data:
  {{ .Values.deployment.mongourlkey }}: {{ .Values.secret.mongodburl }}
  DBNAME: {{ .Values.secret.dbname }}
  COLLECTIONNAME: {{ .Values.secret.collectionName }}
  HOST: {{ .Values.secret.host }}
  PORT: {{ .Values.secret.port }}
  USER: {{ .Values.secret.user }}
  PASSWORD: {{ .Values.secret.password }}