---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: echo-prod
  chart:
    git: git@github.com:ToviKolitz/helm-operator-update-image
    path: charts/myechochart
    ref: master
  values:
    image:
      repository: tovaklein/echo
      tag: 0.4.30
    replicaCount: 3
    ingress:
      host: prod.tovaecho1.tk
    secret:
      mongodburl: bW9uZ29kYjovL3RvdmE6MTIzNDU2QGVjaG8tcHJvZC1tb25nb2RiLTAuZWNoby1wcm9kLW1vbmdvZGItaGVhZGxlc3M6MjcwMTcsZWNoby1wcm9kLW1vbmdvZGItMS5lY2hvLXByb2QtbW9uZ29kYi1oZWFkbGVzczoyNzAxNy9lY2hv
      dbname: ZWNobw==
      collectionName: ZWNob3M=
      host: ZWNoby1wcm9kLW1vbmdvZGItMC5lY2hvLXByb2QtbW9uZ29kYi1oZWFkbGVzcyxlY2hvLXByb2QtbW9uZ29kYi0wLmVjaG8tcHJvZC1tb25nb2RiLWhlYWRsZXNz
      port: MjcwMTc=
      user: dG92YQ==
      password: MTIzNDU2
      secretName: echo-app-secret


      #mongodb://tova:123456@echo-rc-mongodb-0.echo-rc-mongodb-headless:27017,echo-rc-mongodb-1.echo-prod-rc-headless:27017/echo
      #echo-rc-mongodb-0.echo-rc-mongodb-headless,echo-rc-mongodb-1.echo-prod-rc-headless
