---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: echo-prod
  chart:
    git: git@github.com:ToviKolitz/helm-operator-update-image
    path: charts/myechochart
    ref: master
  values:
    deployment:
      image:
        repository: tovaklein/echo
        tag: 0.4.11
      replicaCount: 3
