---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:ToviKolitz/helm-operator-update-image
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: gcr.io/k8s-my-firs-project/echo
      tag: stg-1.1.0
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
