---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echo-rc
  chart:
    git: git@github.com:ToviKolitz/helm-operator-update-image
    path: charts/myechochart
    ref: master
  values:
    image:
      repository: tovaklein/echo
      tag: stg-1.1.0
    replicaCount: 3
    ingress:
      host: stg.tovaecho1.tk
    secret:
      mongodburl: bW9uZ29kYjovL3RvdmE6MTIzNDU2QGVjaG8tcmMtbW9uZ29kYi0wLmVjaG8tcmMtbW9uZ29kYi1oZWFkbGVzczoyNzAxNyxlY2hvLXJjLW1vbmdvZGItMS5lY2hvLXByb2QtcmMtaGVhZGxlc3M6MjcwMTcvZWNobw==
      dbname: ZWNobw==
      collectionName: ZWNob3M=
      host: ZWNoby1yYy1tb25nb2RiLTAuZWNoby1yYy1tb25nb2RiLWhlYWRsZXNzLGVjaG8tcmMtbW9uZ29kYi0xLmVjaG8tcHJvZC1yYy1oZWFkbGVzcw==
      port: MjcwMTc=
      user: dG92YQ==
      password: MTIzNDU2
      secretName: echo-app-secret
