apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "{{ .Values.issuer.issuerName }}"
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  tls:
    # - hosts:
    #     - {{ .Values.ingress.host }}
    #   secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: {{ .Values.ingress.pathType }}
            path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ .Values.service.serviceName }}
                port:
                  number: {{ .Values.deployment.appPort }}